
//POSTS
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILED = 'ADD_POST_FAILED';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

//ERRORS
export const GET_ERRORS = 'GET_ERRORS';